# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/498793ff-ee96-4f1b-9b5c-0f1f057d1950";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b116d08d-70d2-4144-96cd-470542d1cb22".device = "/dev/disk/by-uuid/b116d08d-70d2-4144-96cd-470542d1cb22";
  boot.initrd.luks.devices."luks-a433c35b-f59a-4b4c-9c45-71331f09a0b3".device = "/dev/disk/by-uuid/a433c35b-f59a-4b4c-9c45-71331f09a0b3";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3A6A-7EF2";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/95d15696-7573-491b-89a2-0d40b8257b5a";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
