#!/usr/bin/env -S brew ruby

module Homebrew
  module_function

  # Formula name needs to be passed as first argument
  formula = ARGV.first

  # Get livecheck info
  json = Utils.popen_read HOMEBREW_BREW_FILE, 'livecheck',
                          '--quiet',
                          '--newer-only',
                          '--full-name',
                          '--json',
                          formula

  # Parse livecheck output
  json = JSON.parse json

  # Exit if empty output
  exit if json.empty?

  # Get info about formula
  version = json.first['version']['latest']

  # Finally bump the formula
  safe_system HOMEBREW_BREW_FILE, 'bump-formula-pr',
       '--no-audit',
       '--no-browse',
       "--version=#{version}",
       formula
end
