#!/usr/bin/env bash
#
# example parameter: https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/Class-XSAccessor-1.19.tar.gz

set -euo pipefail

# Class-XSAccessor
function get_name_from_url() {
    local name="${1##*/}"
    echo "${name%-*}"
}

# sha256
function get_hash() {
    echo "$(wget -q "$1" -O - | sha256sum | cut -d' ' -f1)"
}

if test -f "$1"; then
    urls=$(cat "$1")
else
    urls=$@
fi

# print resource(s)
for url in $urls; do
    if ! wget --spider --quiet "$url"; then
        echo "wrong url: $url"
        exit 1
    fi

    cat <<-EOF
resource "$(get_name_from_url "$url")" do
  url "$url"
  sha256 "$(get_hash "$url")"
end

EOF
done

# extra separator
echo

# print stage(s)
for url in $urls; do
    cat <<-EOF
resource("$(get_name_from_url "$url")").stage do
  system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
  system "make"
  system "make", "install"
end

EOF
done
