#!/bin/bash

set -euo pipefail

saved_settings="$HOME/.config/dconf/user.ini"
current_settings="/tmp/dconf_user.ini"

dconf dump / > "$current_settings"

if test -f "$saved_settings"; then
    if diff -q "$saved_settings" "$current_settings" &>/dev/null; then
        echo "Already up-to-date"
    else
        echo "New changes detected"
        echo
        diff -u "$saved_settings" "$current_settings" || true
        echo
        read -p "Confirm overwrite?"
        cat "$current_settings" > "$saved_settings"
    fi
fi


