#!/usr/bin/env bash

set -euo pipefail

QUERY="
SELECT DISTINCT source FROM sources
WHERE uploaders LIKE '%$DEBEMAIL%' OR maintainer LIKE '%$DEBEMAIL%';
"

PGPASSWORD=udd-mirror psql \
    --host=udd-mirror.debian.net \
    --user=udd-mirror \
    -qAtX \
    -c "$QUERY" \
    udd
