#!/usr/bin/env bash

set -euo pipefail

url="$1"
parts=($(echo "$1" | tr '/', ' '))
site="$(echo "${parts[0]}" | cut -d'.' -f1)"
user="${parts[1]}"
repo="${parts[2]}"
package="$(echo "golang-${site}-${user}-${repo}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')"

shift

if test "$(dh-make-golang search "$url")" != ""; then
    echo "Package already exists in Debian archive"
    exit 1
fi

dh-make-golang $@ "$url"
cd "$package"
dh-make-golang create-salsa-project "$package" || true

git remote set-url origin "git@salsa.debian.org:go-team/packages/$package"

cat > debian/gbp.conf <<EOF
[DEFAULT]
debian-branch=debian/sid
upstream-branch=upstream
upstream-tag=upstream/%(version)s

[clone]
postclone=origtargz
EOF
