#!/usr/bin/env bash

set -euo pipefail

name="$1"
file="$HOME/bin/$name"

test -f "$file" && echo exists && exit 1

cat <<-EOF > "$file"
#!/usr/bin/env bash

set -euo pipefail
EOF

chmod +x "$file"

$EDITOR "$file"
