#!/usr/bin/env bash

set -euo pipefail

function ask() {
    read -p "$1 [y/N]? " choice
    [[ "$choice" =~ ^y$ ]] && return 0
    return 1
}

function header() {
    echo ">>>>>>>>>>>>>>>>>>> $1"
}

cd ~/nix

header 'flake'
if ask 'Update flake'; then
    nix flake update
    git add flake.lock
fi

header 'NixOS'
if ask 'Show NixOS changes'; then
    sudo nixos-rebuild build --flake ".#"
    nix store diff-closures /run/current-system ./result
    sudo rm -f result
fi
if ask 'Switch NixOS generation'; then
    sudo nixos-rebuild switch --flake ".#"
fi
if ask 'Clean NixOS generations'; then
    sudo nix-collect-garbage -d
fi

header 'home-manager'
if ask 'Show home-manager changes'; then
    home-manager build --flake ".#$USER"
    nix store diff-closures ~/.local/state/nix/profiles/home-manager ./result
    rm -f result
fi
if ask 'Switch home-manager generation'; then
    home-manager switch --flake ".#$USER"
fi
if ask 'Clean home-manager generations'; then
    nix-collect-garbage -d
fi

