#!/usr/bin/env bash

set -euo pipefail

function ask() {
    read -p "$1 [y/N]? " choice
    [[ "$choice" =~ ^y$ ]] && return 0
    return 1
}

function header() {
    echo ">>>>>>>>>>>>>>>>>>> $1"
}

cd ~/nix

header 'flake'
if ask 'Update flake'; then
    nix flake update
    git add flake.lock
fi

header 'NixOS'
if ask 'Diff NixOS'; then
    sudo nixos-rebuild build --flake ".#"
    nix store diff-closures /run/current-system ./result
    sudo rm -f result
fi
if ask 'Switch NixOS'; then
    sudo nixos-rebuild switch --flake ".#"
fi

header 'home-manager'
if ask 'Diff home-manager'; then
    home-manager build --flake ".#$USER"
    nix store diff-closures ~/.local/state/nix/profiles/home-manager ./result
    rm -f result
fi
if ask 'Switch home-manager'; then
    home-manager switch --flake ".#$USER"
fi

