#!/usr/bin/env bash

set -euo pipefail

nixos-anywhere -- \
    --flake ".#$1" \
    --generate-hardware-config nixos-generate-config "./configs/nixos/$1/hardware-configuration.nix" \
    --no-substitute-on-destination \
    --target-host "$2"
