#!/usr/bin/env bash

set -euo pipefail

nix --experimental-features "nix-command flakes" run ".#nixosConfigurations.${1}.config.system.build.diskoScript"

nixos-install --no-root-passwd --no-channel-copy --flake ".#${1}"
