#!/usr/bin/env bash

set -euo pipefail

if [[ "$1" == 'cli' ]]; then
    xserver=false
elif [[ "$1" == 'gui' ]]; then
    xserver=true
else
    echo "Wrong variant: $1"
    exit 1
fi

shift

cat > /tmp/nixos-vm-config <<EOF
{ config, pkgs, modulesPath, ... }: {
    imports = [(modulesPath + "/profiles/qemu-guest.nix")];

    environment.systemPackages = with pkgs; [ $@ ];

    users.users."$USER" = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        password = "";
    };

    security.sudo.wheelNeedsPassword = false;

    services.xserver.enable = $xserver;
    services.xserver.displayManager.gdm.enable = config.services.xserver.enable;
    services.xserver.desktopManager.gnome.enable = config.services.xserver.enable;
    services.displayManager.autoLogin.enable = config.services.xserver.enable;
    services.displayManager.autoLogin.user = "$USER";

    system.stateVersion = config.system.nixos.release;

    virtualisation.vmVariant = {
        virtualisation.cores = 4;
        virtualisation.memorySize = 4096;
        virtualisation.diskSize = 4096;
        virtualisation.diskImage = null;
        virtualisation.graphics = config.services.xserver.enable;
        virtualisation.qemu.options = [
          "-device virtio-vga"
          "-display gtk,grab-on-hover=on"
        ];
    };
}
EOF

nix-build "$PWD/nixos" -A vm -I nixpkgs="$PWD" -I nixos-config=/tmp/nixos-vm-config

"$PWD/result/bin/run-nixos-vm"
