#!/usr/bin/env bash

set -euo pipefail

cat > /tmp/nixos-vm-gnome-config <<EOF
{ config, pkgs, modulesPath, ... }: {
    imports = [(modulesPath + "/profiles/qemu-guest.nix")];

    environment.systemPackages = with pkgs; [ ${@} ];

    users.users."${USER}" = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        initialPassword = "${USER}";
    };

    services.xserver.enable = true;
    services.xserver.displayManager.gdm.enable = true;
    services.xserver.desktopManager.gnome.enable = true;
    services.displayManager.autoLogin = {
        enable = true;
        user = "${USER}";
    };

    system.stateVersion = config.system.nixos.release;

    virtualisation.vmVariant = {
        virtualisation.cores = 4;
        virtualisation.memorySize = 4096;
        virtualisation.diskSize = 4096;
        virtualisation.diskImage = null;
        virtualisation.graphics = true;
        virtualisation.qemu.options = [
          "-device virtio-vga"
          "-display gtk,grab-on-hover=on"
        ];
    };
}
EOF

nix-build "$PWD/nixos" -A vm -I nixpkgs="$PWD" -I nixos-config=/tmp/nixos-vm-gnome-config

"$PWD/result/bin/run-nixos-vm"
