#!/usr/bin/env bash

set -euo pipefail

diskoScript="$(nix --experimental-features "nix-command flakes" build --print-out-paths --no-link ".#nixosConfigurations.${1}.config.system.build.diskoScript")"
nixosSystem="$(nix --experimental-features "nix-command flakes" build --print-out-paths --no-link ".#nixosConfigurations.${1}.config.system.build.toplevel")"

"${diskoScript}"

nixos-install --no-root-passwd --no-channel-copy --system "$nixosSystem"
