#!/usr/bin/env ruby

passwords = %W[
  TKEK17099W3
  TKEK17009W3
  TKEK17099W3cz
  TKEK17009W3cz
  TKEK17099WJK
  TKEK17099WRK
  TKEK17009WRK
  TKEK17099RK
  TKEK17009RK
  RK
  wyklad
  haslo
  H
  Haslo
  TKEK17099W
  TKEK17009w
  TKEK17099H
  TKEK17009H
  TKEK17099WH
  TKEK17009WH
]

ARGV.each do |file|
  pass = passwords.find do |pass|
    if system "qpdf", "--decrypt", "--replace-input", "--password=#{pass}", file, out: File::NULL, err: File::NULL
      break pass
    end
  end

  if pass
    puts "#{file}: #{pass}"
  end
end
