#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'colorize' # https://github.com/fazibear/colorize

# Class Git
class Git
  attr_reader :name
  attr_reader :path

  def initialize(name, work_tree, git_dir = nil)
    @name = name
    @path = git_dir || work_tree
    git_dir = "#{work_tree}/.git" if git_dir.nil?
    @args = "--git-dir=#{git_dir} --work-tree=#{work_tree}"
  end

  def dirty?
    dirty = `git #{@args} status -s`.chomp
    if dirty.empty?
      false
    else
      true
    end
  end

  def status
    `git #{@args} status -s`.chomp
  end

  def sync
    `git #{@args} pull --rebase`
    `git #{@args} push`
  end

  def ahead
    `git #{@args} rev-list --count @{u}..`.chomp
  end

  def behind
    `git #{@args} fetch origin`
    `git #{@args} rev-list --count ..@{u}`.chomp
  end
end

sync = false
parser = OptionParser.new
parser.on('-s', '--sync', 'pull --rebase and push in all repos') do
  sync = true
end
parser.parse!

[
  Git.new('ansible', File.join(Dir.home, 'ansible')),
  Git.new('scripts', File.join(Dir.home, 'bin')),
  Git.new('dotfiles', Dir.home, File.join(Dir.home, '.dotfiles')),
  Git.new('keys', Dir.home, File.join(Dir.home, '.keys')),
].each do |repo|
  dirty = repo.dirty?
  puts "#{'==>'.blue.bold} #{repo.name.bold} #{repo.path.underline}"
  puts "#{' ==>'.yellow.bold} ahead #{repo.ahead.bold} commits" unless repo.ahead.to_i.zero?
  puts "#{' ==>'.red.bold} behind #{repo.behind.bold} commits" unless repo.behind.to_i.zero?
  if dirty
    puts "#{repo.status}"
  elsif sync
    repo.sync
  end
end
