name: Build flake

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: build-flake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: /nix
          build-mount-path-ownership: root:root
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: ${{ github.repository_owner }}
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Build flake
        run: nix flake check
